# For more information: https://github.com/julien-r44/adonis-sail
services:
  pgsql:
    image: 'postgres:15'
    ports:
      - '${PG_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${PG_PASSWORD:-secret}'
      POSTGRES_DB: '${PG_DB_NAME:-default}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD:-secret}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/data'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${PG_DB_NAME:-default}", "-U", "${PG_USER}"]
      retries: 3
      timeout: 5s

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${MAILHOG_PORT:-1025}:1025'
      - '${MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail


networks:
  sail:
    driver: bridge

volumes:
  sailpgsql:
